name: Automatic Report generation
on:
  push:
    branches: [main]
    paths: ["tests/**", "spec/*.html"]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Generate Reports using NodeJS

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run generate
      - run: |
          git config user.name "Report generation bot"
          git config user.email "<>"
          git add -f tests/*.html
          git commit -am "Automated report generation"
      - name: Push files
        uses: int128/update-generated-files-action@v2
